"""empty message

Revision ID: 37756ca8df6c
Revises: b6b8ed8cb17c
Create Date: 2022-06-04 13:23:23.836364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37756ca8df6c'
down_revision = 'b6b8ed8cb17c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Artist', ['name'])
    op.create_unique_constraint(None, 'Venue', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='unique')
    op.drop_constraint(None, 'Artist', type_='unique')
    # ### end Alembic commands ###
