"""empty message

Revision ID: b6b8ed8cb17c
Revises: 36f06ede463d
Create Date: 2022-06-03 12:38:32.732309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6b8ed8cb17c'
down_revision = '36f06ede463d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('available_from', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'available_from')
    # ### end Alembic commands ###
