"""empty message

Revision ID: c67bdf246d41
Revises: eb4c7a985374
Create Date: 2022-06-03 12:37:20.103030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c67bdf246d41'
down_revision = 'eb4c7a985374'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('available_till', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'available_till')
    # ### end Alembic commands ###
