"""empty message

Revision ID: e3dca976ac66
Revises: 29e95e5dc4a5
Create Date: 2022-06-03 10:07:55.107014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3dca976ac66'
down_revision = '29e95e5dc4a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('available_from', sa.DateTime(), nullable=True))
    op.add_column('Artist', sa.Column('available_till', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'available_till')
    op.drop_column('Artist', 'available_from')
    # ### end Alembic commands ###
