"""empty message

Revision ID: ed8c4f041f06
Revises: 37756ca8df6c
Create Date: 2022-06-04 13:24:10.537738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed8c4f041f06'
down_revision = '37756ca8df6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Artist_name_key', 'Artist', type_='unique')
    op.drop_constraint('Venue_name_key', 'Venue', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Venue_name_key', 'Venue', ['name'])
    op.create_unique_constraint('Artist_name_key', 'Artist', ['name'])
    # ### end Alembic commands ###
